BookStore/BookStore.Presentation/Areas/Admin/Controllers/CategoryManagementController.cs
using AutoMapper;
using BookStore.BusinessLogicLayer;
using BookStore.Helpers;
using BookStore.Models;
using BookStore.Presentation.Areas.Admin.ViewModels;
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace BookStore.Presentation.Areas.Admin.Controllers
{
    [Authorize(Roles = "Administrators, Manager")]
    public class CategoryManagementController : Controller
    {
        private readonly ICategoryService _categoryService;

        public CategoryManagementController(ICategoryService categoryServices)
        {
            _categoryService = categoryServices;
        }

        public async Task<ActionResult> Index(string sortOrder, string currentFilter,
            string searchString, int? page)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = sortOrder.IsBlank() ? "name_desc" : "";
            ViewData["TotalSortParm"] = sortOrder == "Total" ? "total_desc" : "Total";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            Expression<Func<Category, bool>> filter = null;
            Func<IQueryable<Category>, IOrderedQueryable<Category>> orderBy = null;

            if (searchString.IsNotBlank())
            {
                filter = a => a.CategoryName.Contains(searchString);
            }
            switch (sortOrder)
            {
                case "name_desc":
                    orderBy = b => b.OrderByDescending(s => s.CategoryName);
                    break;
                case "Total":
                    orderBy = b => b.OrderBy(s => s.Books.Count());
                    break;
                case "total_desc":
                    orderBy = b => b.OrderByDescending(s => s.Books.Count());
                    break;
                default:
                    orderBy = b => b.OrderBy(s => s.CategoryName);
                    break;
            }

            var categories = await _categoryService.GetAsync(filter: filter, orderBy: orderBy, page: page ?? 1, pageSize: 10);

            return View(categories);
        }

        public ActionResult AddCategory()
        {
            var categoryEditViewModel = new CategoryEditViewModel();
            return View(categoryEditViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult AddCategory(CategoryEditViewModel categoryEditViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(categoryEditViewModel);
            }

            var category = Mapper.Map<Category>(categoryEditViewModel);

            _categoryService.Create(category);

            return RedirectToAction("Index");
        }

        public ActionResult EditCategory(int id)
        {
            var category = _categoryService.GetById(id);

            var categoryEditViewModel = Mapper.Map<CategoryEditViewModel>(category);

            return View(categoryEditViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult EditCategory(CategoryEditViewModel categoryEditViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(categoryEditViewModel);
            }

            var category = Mapper.Map<Category>(categoryEditViewModel);
            _categoryService.Update(category);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult DeleteCategory(int id)
        {
            _categoryService.Delete(id);

            return RedirectToAction("Index");
        }

        [AcceptVerbs("Get", "Post")]
        public ActionResult CheckIfCategoryNameAlreadyExists([Bind(Prefix = "Category.CategoryName")]string name)
        {
            var category = _categoryService.Find(b => b.CategoryName == name);
            return category == null ? Json(true) : Json("Category name exists");
        }
    }
}

BookStore/BookStore.Presentation/Areas/Admin/Views/CategoryManagement/AddCategory.cshtml
@using BookStore.ViewModels
@model CategoryEditViewModel
@{
    ViewBag.Title = "Add Category";
}
<h2>Add Category</h2>
<hr />

<form action="/Admin/CategoryManagement/AddCategory" method="post" class="row form-horizontal">
    @Html.AntiForgeryToken()
    <div class="col">
        <div class="form-group">
            <label name="Name" class="control-label">Category Name:</label>
            <div>
                <input type="text" name="CategoryName" class="form-control" value="@Model.CategoryName" />
                @Html.ValidationMessageFor(m => m.CategoryName, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="col">
        <div class="form-group">
            <label class="control-label">Description:</label>
            <div>
                <textarea class="form-control" name="Description" id="ckeditor"></textarea>
                @Html.ValidationMessageFor(m => m.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <input type="submit" class="btn btn-primary" value="Add" />
            <a href="/Admin/AuthorManagement" class="btn btn-secondary">Cancel</a>
        </div>
    </div>
</form>

@section scripts {
    <script src="~/Assets/js/ckeditor/ckeditor.js"></script>
    <script src="~/Assets/js/ckeditor/ckeditorconfig.js"></script>
} 

BookStore/BookStore.Presentation/Areas/Admin/Views/CategoryManagement/EditCategory.cshtml
@model CategoryEditViewModel
@{
    /**/

    ViewBag.Title = "Edit Category";
}
<script src="~/Assets/js/ckeditor/ckeditor.js"></script>
<h2>Edit Category</h2>
<hr />

<form action="/Admin/CategoryManagement/EditCategory" method="post" class="row form-horizontal">
    @Html.AntiForgeryToken()
    <div class="col">
        <div class="form-group">
            <label name="CategoryId" class="control-label">Category Id:</label>
            <div>
                <input type="text" name="CategoryId" class="form-control" readonly="readonly" value="@Model.CategoryId" />
                @Html.ValidationMessageFor(m => m.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label name="Name" class="control-label">Category Name:</label>
            <div>
                <input type="text" name="CategoryName" class="form-control" value="@Model.CategoryName" />
                @Html.ValidationMessageFor(m => m.CategoryName, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="col">
        <div class="form-group">
            <label class="control-label">Description:</label>
            <div>
                <textarea class="form-control" name="Description" id="ckeditor">@Model.Description</textarea>
                @Html.ValidationMessageFor(m => m.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <input type="submit" class="btn btn-primary" value="Update" />
            <a href="/Admin/CategoryManagement" class="btn btn-secondary">Cancel</a>
        </div>
    </div>
</form>

@section scripts {
    <script src="~/Assets/js/ckeditor/ckeditor.js"></script>
    <script src="~/Assets/js/ckeditor/ckeditorconfig.js"></script>
}

BookStore/BookStore.Presentation/Areas/Admin/Views/CategoryManagement/Index.cshtml
@model PaginatedList<Category>
@{
    ViewBag.Title = "Category Management";
}

<h2>Category Management</h2>
<hr />
<div>
    <a href="@Url.Action("AddCategory", "CategoryManagement")" class="btn btn-primary float-left">Add Category</a>

    <form action="@Url.Action("Index", "CategoryManagement")" method="get" class="form-inline float-right">

        @*<div class="form-group mx-sm-3 mb-2">
                <label class="my-1 mr-2" for="sortOrder">Order By:</label>
                <select class="custom-select my-1 mr-sm-2" id="orderBy">
                    <option value="1">Price Up</option>
                    <option value="2">Price Down</option>
                </select>
            </div>*@
        <div class="form-group mx-sm-3 mb-2">
            <label for="inputSearch" class="control-label mr-3">Input: </label>
            <input type="text" class="form-control mr-3" id="inputSearch" name="SearchString" value="@ViewData["currentFilter"]" placeholder="Input....">
            <input type="submit" class=" form-control btn btn-primary mr-3" value="Search" /> |
            <a href="/Admin/CategoryManagement/Index" class="btn btn-default">Back to Full List</a>
        </div>

    </form>
</div>

@if (!Model.Any())
{
    <tr><td colspan="3" class="text-center">Don't have a category yet.</td></tr>
}
else
{
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            @{
                var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
                var nextDisabled = !Model.HasNextPage ? "disabled" : "";
                ViewBag.PageRange = 3;
            }
            <li class="page-item">
                <a href="@Url.Action("Index", "CategoryManagement", new { sortOrder=ViewData["CurrentSort"], page=1, currentFilter=ViewData["CurrentFilter"] })"
                   class="btn page-link @prevDisabled"><<</a>
            <li class="page-item">
                <a href="@Url.Action("Index", "CategoryManagement", new { sortOrder=ViewData["CurrentSort"], page=(Model.PageIndex - 1 <= 0 ? 1 : Model.PageIndex - 1), currentFilter=ViewData["CurrentFilter"] })"
                   class="btn page-link @prevDisabled"><</a>
            </li>
            @for (int i = 1; i <= Model.TotalPages; i++)
            {
                if (i >= Model.PageIndex - ViewBag.PageRange && i <= Model.PageIndex + ViewBag.PageRange)
                {
                    <li class="page-item">
                        <a class="@(i==Model.PageIndex ? "Current" : "") page-link"
                           href="@Url.Action("Index", "CategoryManagement", new { sortOrder=ViewData["CurrentSort"], page=i, currentFilter=ViewData["CurrentFilter"] })">@i</a>
                    </li>
                }
                @*<li class="page-item"><a class="page-link" href="@Url.Action("Index", "BookManagement", new { sortOrder=ViewData["CurrentSort"], page=i, currentFilter=ViewData["CurrentFilter"] })">@i</a></li>*@
            }
            <li class="page-item">
                <a href="@Url.Action("Index", "CategoryManagement", new { sortOrder=ViewData["CurrentSort"], page=(Model.PageIndex + 1 > Model.TotalPages ? Model.TotalPages : Model.PageIndex + 1), currentFilter=ViewData["CurrentFilter"] })"
                   class="btn page-link @nextDisabled">></a>
            <li class="page-item">
                <a href="@Url.Action("Index", "CategoryManagement", new { sortOrder=ViewData["CurrentSort"], page=(Model.TotalPages), currentFilter=ViewData["CurrentFilter"] })"
                   class="btn page-link @nextDisabled">>></a>
        </ul>
    </nav>

    <table class="table table-condensed table-bordered">
        <tr class="d-flex">
            <th class="col-md-2">
                <a href="@Url.Action("Index", "CategoryManagement", new { sortOrder = ViewData["NameSortParm"], currentFilter = ViewData["CurrentFilter"] })">Category Name</a>
            </th>
            <th class="col-md-6">Description</th>
            <th class="col-md-2">
                <a href="@Url.Action("Index", "CategoryManagement", new { sortOrder = ViewData["TotalSortParm"], currentFilter = ViewData["CurrentFilter"] })">Total Books</a>
            </th>
            <th class="col-md-2">Manage</th>
        </tr>

        @foreach (var category in Model)
        {
            <tr class="d-flex">
                <td class="col-md-2">
                    @category.CategoryName
                </td>
                <td class="col-md-6">
                    @Html.Raw(category.Description)
                </td>
                <td class="col-md-2 text-center">
                    @category.Books.Count()
                </td>
                <td class="col-md-2">
                    <form action="/Admin/CategoryManagement/DeleteCategory/@category.CategoryId" method="post">
                        <a href="/Admin/CategoryManagement/EditCategory/@category.CategoryId" class="btn btn-primary">Edit</a>
                        <button type="submit" onclick="return confirm('Are you sure to delete this category?');" class="btn btn-danger">Delete</button>
                    </form>
                </td>
            </tr>
        }
    </table>
}