BookStore/BookStore.Presentation/Areas/Admin/Controllers/PublisherManagementController.cs
using AutoMapper;
using BookStore.BusinessLogicLayer;
using BookStore.Helpers;
using BookStore.Models;
using BookStore.Presentation.Areas.Admin.ViewModels;
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace BookStore.Presentation.Areas.Admin.Controllers
{
    [Authorize(Roles = "Administrators, Manager")]
    public class PublisherManagementController : Controller
    {
        private readonly IPublisherService _publisherServices;

        public PublisherManagementController(IPublisherService publisherServices)
        {
            _publisherServices = publisherServices;
        }

        public async Task<ActionResult> Index(string sortOrder, string currentFilter,
            string searchString, int? page)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = sortOrder.IsBlank() ? "name_desc" : "";
            ViewData["TotalSortParm"] = sortOrder == "Total" ? "total_desc" : "Total";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            Expression<Func<Publisher, bool>> filter = null;
            Func<IQueryable<Publisher>, IOrderedQueryable<Publisher>> orderBy = null;

            if (searchString.IsNotBlank())
            {
                filter = a => a.PublisherName.Contains(searchString);
            }
            switch (sortOrder)
            {
                case "name_desc":
                    orderBy = b => b.OrderByDescending(s => s.PublisherName);
                    break;
                case "Total":
                    orderBy = b => b.OrderBy(s => s.Books.Count());
                    break;
                case "total_desc":
                    orderBy = b => b.OrderByDescending(s => s.Books.Count());
                    break;
                default:
                    orderBy = b => b.OrderBy(s => s.PublisherName);
                    break;
            }

            var publishers = await _publisherServices.GetAsync(filter: filter, orderBy: orderBy, page: page ?? 1, pageSize: 10);

            return View(publishers);
        }

        public ActionResult AddPublisher()
        {
            var publisherEditViewModel = new PublisherEditViewModel();
            return View(publisherEditViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult AddPublisher(PublisherEditViewModel publisherEditViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(publisherEditViewModel);
            }

            var publisher = Mapper.Map<Publisher>(publisherEditViewModel);

            _publisherServices.Create(publisher);

            return RedirectToAction("Index");
        }

        public ActionResult EditPublisher(int id)
        {
            var publisher = _publisherServices.GetById(id);

            var publisherEditViewModel = Mapper.Map<PublisherEditViewModel>(publisher);

            return View(publisherEditViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult EditPublisher(PublisherEditViewModel publisherEditViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(publisherEditViewModel);
            }

            var publisher = Mapper.Map<Publisher>(publisherEditViewModel);
            _publisherServices.Update(publisher);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult DeletePublisher(int id)
        {
            _publisherServices.Delete(id);

            return RedirectToAction("Index");
        }

        [AcceptVerbs("Get", "Post")]
        public ActionResult CheckIfPublisherNameAlreadyExists([Bind(Prefix = "Publisher.PublisherName")]string name)
        {
            var publisher = _publisherServices.Find(b => b.PublisherName == name);
            return publisher == null ? Json(true) : Json("Publisher name is exists");
        }
    }
}

BookStore/BookStore.Presentation/Areas/Admin/Views/PublisherManagement/AddPublisher.cshtml
@model PublisherEditViewModel
@{
    ViewBag.Title = "Add Publisher";
}
<script src="~/Assets/js/ckeditor/ckeditor.js"></script>
<h2>Add Publisher</h2>
<hr />

<form action="/Admin/PublisherManagement/AddPublisher" method="post" class="row form-horizontal">
    @Html.AntiForgeryToken()
    <div class="col">
        <div class="form-group">
            <label name="Name" class="control-label">Publisher Name:</label>
            <div>
                <input type="text" name="PublisherName" class="form-control" value="@Model.PublisherName" />
                @Html.ValidationMessageFor(m => m.PublisherName, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="col">
        <div class="form-group">
            <label class="control-label">Description:</label>
            <div>
                <textarea class="form-control" name="Description" id="ckeditor"></textarea>
                @Html.ValidationMessageFor(m => m.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <input type="submit" class="btn btn-primary" value="Add" />
            <a href="/Admin/PublisherManagement" class="btn btn-secondary">Cancel</a>
        </div>
    </div>
</form>

@section scripts {
    <script src="~/Assets/js/ckeditor/ckeditor.js"></script>
    <script src="~/Assets/js/ckeditor/ckeditorconfig.js"></script>
} 

BookStore/BookStore.Presentation/Areas/Admin/Views/PublisherManagement/EditPublisher.cshtml
@model PublisherEditViewModel
@{
    ViewBag.Title = "Edit Publisher";
}
<script src="~/Assets/js/ckeditor/ckeditor.js"></script>
<h2>Edit Publisher</h2>
<hr />
<form action="/Admin/PublisherManagement/EditPublisher" method="post" class="row form-horizontal">
    @Html.AntiForgeryToken()
    <div class="col">
        <div class="form-group">
            <label name="PublisherId" class="control-label">PublisherId:</label>
            <div>
                <input type="text" name="PublisherId" class="form-control" readonly="readonly" value="@Model.PublisherId" />
                @Html.ValidationMessageFor(m => m.PublisherId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label name="Name" class="control-label">Publisher Name:</label>
            <div>
                <input type="text" name="PublisherName" class="form-control" value="@Model.PublisherName" />
                @Html.ValidationMessageFor(m => m.PublisherName, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="col">
        <div class="form-group">
            <label class="control-label">Description:</label>
            <div>
                <textarea class="form-control" name="Description" id="ckeditor">@Model.Description</textarea>
                @Html.ValidationMessageFor(m => m.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <input type="submit" class="btn btn-primary" value="Update" />
            <a href="/Admin/PublisherManagement/Index" class="btn btn-secondary">Cancel</a>
        </div>
    </div>
</form>

@section scripts {
    <script src="~/Assets/js/ckeditor/ckeditor.js"></script>
    <script src="~/Assets/js/ckeditor/ckeditorconfig.js"></script>
} 

BookStore/BookStore.Presentation/Areas/Admin/Views/PublisherManagement/Index.cshtml
@model PaginatedList<Publisher>
@{
    ViewBag.Title = "Publisher Management";
}

<h2>Publisher Management</h2>
<hr />
<div>
    <a href="@Url.Action("AddPublisher", "PublisherManagement")" class="btn btn-primary float-left">Add Publisher</a>

    <form action="@Url.Action("Index", "PublisherManagement")" method="get" class="form-inline float-right">

        @*<div class="form-group mx-sm-3 mb-2">
                <label class="my-1 mr-2" for="sortOrder">Order By:</label>
                <select class="custom-select my-1 mr-sm-2" id="orderBy">
                    <option value="1">Price Up</option>
                    <option value="2">Price Down</option>
                </select>
            </div>*@
        <div class="form-group mx-sm-3 mb-2">
            <label for="inputSearch" class="control-label mr-3">Input: </label>
            <input type="text" class="form-control mr-3" id="inputSearch" name="SearchString" value="@ViewData["currentFilter"]" placeholder="Input....">
            <input type="submit" class=" form-control btn btn-primary mr-3" value="Search" /> |
            <a href="/Admin/PublisherManagement/Index" class="btn btn-default">Back to Full List</a>
        </div>

    </form>
</div>

@if (!Model.Any())
{
    <tr><td colspan="3" class="text-center">Don't have a publisher yet.</td></tr>
}
else
{
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            @{
                var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
                var nextDisabled = !Model.HasNextPage ? "disabled" : "";
                ViewBag.PageRange = 3;
            }
            <li class="page-item">
                <a href="@Url.Action("Index", "PublisherManagement", new { sortOrder=ViewData["CurrentSort"], page=1, currentFilter=ViewData["CurrentFilter"] })"
                   class="btn page-link @prevDisabled"><<</a>
            <li class="page-item">
                <a href="@Url.Action("Index", "PublisherManagement", new { sortOrder=ViewData["CurrentSort"], page=(Model.PageIndex - 1 <= 0 ? 1 : Model.PageIndex - 1), currentFilter=ViewData["CurrentFilter"] })"
                   class="btn page-link @prevDisabled"><</a>
            </li>
            @for (int i = 1; i <= Model.TotalPages; i++)
            {
                if (i >= Model.PageIndex - ViewBag.PageRange && i <= Model.PageIndex + ViewBag.PageRange)
                {
                    <li class="page-item">
                        <a class="@(i==Model.PageIndex ? "Current" : "") page-link"
                           href="@Url.Action("Index", "PublisherManagement", new { sortOrder=ViewData["CurrentSort"], page=i, currentFilter=ViewData["CurrentFilter"] })">@i</a>
                    </li>
                }
                @*<li class="page-item"><a class="page-link" href="@Url.Action("Index", "BookManagement", new { sortOrder=ViewData["CurrentSort"], page=i, currentFilter=ViewData["CurrentFilter"] })">@i</a></li>*@
            }
            <li class="page-item">
                <a href="@Url.Action("Index", "PublisherManagement", new { sortOrder=ViewData["CurrentSort"], page=(Model.PageIndex + 1 > Model.TotalPages ? Model.TotalPages : Model.PageIndex + 1), currentFilter=ViewData["CurrentFilter"] })"
                   class="btn page-link @nextDisabled">></a>
            <li class="page-item">
                <a href="@Url.Action("Index", "PublisherManagement", new { sortOrder=ViewData["CurrentSort"], page=(Model.TotalPages), currentFilter=ViewData["CurrentFilter"] })"
                   class="btn page-link @nextDisabled">>></a>
        </ul>
    </nav>

    <table class="table table-condensed table-bordered">
        <tr class="d-flex">
            <th class="col-md-2">
                <a href="@Url.Action("Index", "PublisherManagement", new { sortOrder = ViewData["NameSortParm"], currentFilter = ViewData["CurrentFilter"] })">Publisher Name</a>
            </th>
            <th class="col-md-6">Description</th>
            <th class="col-md-2">
                <a href="@Url.Action("Index", "PublisherManagement", new { sortOrder = ViewData["TotalSortParm"], currentFilter = ViewData["CurrentFilter"] })">Total Books</a>
            </th>
            <th class="col-md-2">Manage</th>
        </tr>

        @foreach (var publisher in Model)
        {
            <tr class="d-flex">
                <td class="col-md-2">
                    @publisher.PublisherName
                </td>
                <td class="col-md-6">
                    @Html.Raw(publisher.Description)
                </td>
                <td class="col-md-2 text-center">
                    @publisher.Books.Count()
                </td>
                <td class="col-md-2">
                    <form action="/Admin/PublisherManagement/DeletePublisher/@publisher.PublisherId" method="post">
                        <a href="/Admin/PublisherManagement/EditPublisher/@publisher.PublisherId" class="btn btn-primary">Edit</a>
                        <button type="submit" onclick="return confirm('Are you sure to delete this publisher?');" class="btn btn-danger">Delete</button>
                    </form>
                </td>
            </tr>
        }
    </table>
}