BookStore/BookStore.Presentation/Areas/Admin/Controllers/BookManagementController.cs
using AutoMapper;
using BookStore.BusinessLogicLayer;
using BookStore.Helpers;
using BookStore.Models;
using BookStore.Presentation.Areas.Admin.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace BookStore.Presentation.Areas.Admin.Controllers
{
    [Authorize(Roles = "Administrators, Manager")]
    public class BookManagementController : Controller
    {
        private const string _ImagesPath = "~/Assets/images";
        private readonly IBookService _bookServices;
        private readonly ICategoryService _categoryServices;
        private readonly IAuthorService _authorServices;
        private readonly IPublisherService _publisherServices;

        public BookManagementController(
            IBookService bookServices,
            ICategoryService categoryServices,
            IAuthorService authorServices,
            IPublisherService publisherServices
            )
        {
            _bookServices = bookServices;
            _categoryServices = categoryServices;
            _authorServices = authorServices;
            _publisherServices = publisherServices;
        }

        public async Task<ActionResult> Index(string sortOrder, string currentFilter,
            string searchString, int? page)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["TitleSortParm"] = sortOrder.IsBlank() ? "title_desc" : "";
            ViewData["PriceSortParm"] = sortOrder == "Price" ? "price_desc" : "Price";
            ViewData["QuantitySortParm"] = sortOrder == "Quantity" ? "quantity_desc" : "Quantity";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            Expression<Func<Book, bool>> filter = null;
            Func<IQueryable<Book>, IOrderedQueryable<Book>> orderBy = null;

            if (searchString.IsNotBlank())
            {
                filter = b => b.Title.Contains(searchString);
            }
            switch (sortOrder)
            {
                case "title_desc":
                    orderBy = b => b.OrderByDescending(s => s.Title);
                    break;
                case "Price":
                    orderBy = b => b.OrderBy(s => s.Price);
                    break;
                case "price_desc":
                    orderBy = b => b.OrderByDescending(s => s.Price);
                    break;
                case "Quantity":
                    orderBy = b => b.OrderBy(s => s.Quantity);
                    break;
                case "quantity_desc":
                    orderBy = b => b.OrderByDescending(s => s.Quantity);
                    break;
                default:
                    orderBy = b => b.OrderBy(s => s.Title);
                    break;
            }

            var books = await _bookServices.GetAsync(filter: filter, orderBy: orderBy, page: page ?? 1, pageSize: 10);

            return View(books);
        }

        public async Task<ActionResult> AddBook()
        {
            List<Category> categories = await _categoryServices.GetAsync(orderBy: x => x.OrderBy(b => b.CategoryName), page: 1, pageSize: 10);
            ViewBag.Categories = new SelectList(categories.OrderBy(x => x.CategoryId), "CategoryId", "CategoryName");

            List<Author> authors = await _authorServices.GetAsync(orderBy: x => x.OrderBy(b => b.AuthorName), page: 1, pageSize: 10);
            ViewBag.Authors = new SelectList(authors.OrderBy(x => x.AuthorId), "AuthorId", "AuthorName");

            List<Publisher> publishers = await _publisherServices.GetAsync(orderBy: x => x.OrderBy(b => b.PublisherName), page: 1, pageSize: 10);
            ViewBag.Publishers = new SelectList(publishers.OrderBy(x => x.PublisherId), "PublisherId", "PublisherName");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public async Task<ActionResult> AddBook(BookEditViewModel bookEditViewModel, HttpPostedFileBase ImgUrl)
        {
            if (ModelState.IsValid)
            {
                string fileName = "";
                if (ImgUrl != null && ImgUrl.ContentLength > 0)
                {
                    try
                    {
                        fileName = Path.GetFileName(ImgUrl.FileName);
                        string path = Path.Combine(Server.MapPath(_ImagesPath), Path.GetFileName(ImgUrl.FileName));
                        ImgUrl.SaveAs(path);
                    }
                    catch (Exception)
                    {
                        throw;
                    }
                }
                var book = Mapper.Map<Book>(bookEditViewModel);
                book.ImageUrl = fileName;
                await _bookServices.CreateAsync(book);

                return RedirectToAction("Index");
            }

            List<Category> categories = await _categoryServices.GetAsync(orderBy: x => x.OrderBy(b => b.CategoryName), page: 1, pageSize: 10);
            ViewBag.Categories = new SelectList(categories.OrderBy(x => x.CategoryId), "CategoryId", "CategoryName");

            List<Author> authors = await _authorServices.GetAsync(orderBy: x => x.OrderBy(b => b.AuthorName), page: 1, pageSize: 10);
            ViewBag.Authors = new SelectList(authors.OrderBy(x => x.AuthorId), "AuthorId", "AuthorName");

            List<Publisher> publishers = await _publisherServices.GetAsync(orderBy: x => x.OrderBy(b => b.PublisherName), page: 1, pageSize: 10);
            ViewBag.Publishers = new SelectList(publishers.OrderBy(x => x.PublisherId), "PublisherId", "PublisherName");

            return View(bookEditViewModel);
        }

        public async Task<ActionResult> EditBook(int id)
        {
            var book = await _bookServices.GetByIdAsync(id);
            if (book == null)
            {
                return HttpNotFound();
            }

            var bookEditViewModel = Mapper.Map<BookEditViewModel>(book);

            ViewBag.Categories = new SelectList(await _categoryServices.GetAsync(orderBy: x => x.OrderBy(b => b.CategoryName), page: 1, pageSize: 10), "CategoryId", "CategoryName", bookEditViewModel.CategoryId);
            ViewBag.Authors = new SelectList(await _authorServices.GetAsync(orderBy: x => x.OrderBy(b => b.AuthorName), page: 1, pageSize: 10), "AuthorId", "AuthorName", bookEditViewModel.AuthorId);
            ViewBag.Publishers = new SelectList(await _publisherServices.GetAsync(orderBy: x => x.OrderBy(b => b.PublisherName), page: 1, pageSize: 10), "PublisherId", "PublisherName", bookEditViewModel.PublisherId);

            return View(bookEditViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public async Task<ActionResult> EditBook(BookEditViewModel bookEditViewModel, HttpPostedFileBase ImgUrl)
        {
            if (ModelState.IsValid)
            {

                if (ImgUrl != null && ImgUrl.ContentLength > 0)
                {
                    string filePath = Path.Combine(Server.MapPath(_ImagesPath), Path.GetFileName(ImgUrl.FileName));
                    ImgUrl.SaveAs(filePath);
                    bookEditViewModel.ImageUrl = ImgUrl.FileName;
                }
                var book = Mapper.Map<Book>(bookEditViewModel);
                book.ImageUrl = bookEditViewModel.ImageUrl;
                await _bookServices.UpdateAsync(book);

                return RedirectToAction("Index");
            }

            ViewBag.Categories = new SelectList(await _categoryServices.GetAsync(orderBy: x => x.OrderBy(b => b.CategoryName), page: 1, pageSize: 10), "CategoryId", "CategoryName", bookEditViewModel.CategoryId);
            ViewBag.Authors = new SelectList(await _authorServices.GetAsync(orderBy: x => x.OrderBy(b => b.AuthorName), page: 1, pageSize: 10), "AuthorId", "AuthorName", bookEditViewModel.AuthorId);
            ViewBag.Publishers = new SelectList(await _publisherServices.GetAsync(orderBy: x => x.OrderBy(b => b.PublisherName), page: 1, pageSize: 10), "PublisherId", "PublisherName", bookEditViewModel.PublisherId);
            return View(bookEditViewModel);
        }

        [HttpPost]
        public async Task<ActionResult> DeleteBook(int id)
        {
            await _bookServices.DeleteAsync(id);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<JsonResult> AddCategory(Category category)
        {
            var task = Task.Run(() => _categoryServices.CreateAsync(category));
            var quoteId = await task;
            return Json(quoteId, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async Task<JsonResult> AddPublisher(Publisher publisher)
        {
            var task = Task.Run(() => _publisherServices.CreateAsync(publisher));
            var quoteId = await task;
            return Json(quoteId, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async Task<JsonResult> AddAuthor(Author author)
        {
            var task = Task.Run(() => _authorServices.CreateAsync(author));
            var quoteId = await task;
            return Json(quoteId, JsonRequestBehavior.AllowGet);
        }


        [AcceptVerbs("Get", "Post")]
        public ActionResult CheckIfBookTitleAlreadyExists([Bind(Prefix = "Book.Title")]string title)
        {
            var book = _bookServices.Find(b => b.Title == title);
            return book == null ? Json(true) : Json("Tựa sách này đã có sẵn");
        }
    }
}

BookStore/BookStore.Presentation/Controllers/BookController.cs
using BookStore.BusinessLogicLayer;
using BookStore.Helpers;
using BookStore.Models;
using BookStore.Presentation.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace BookStore.Presentation.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookService _bookServices;
        private readonly ICategoryService _categoryServices;
        private readonly IReviewService _reviewServices;

        public BookController(
            IBookService bookServices,
            ICategoryService categoryServices,
            IReviewService reviewServices
            )
        {
            _bookServices = bookServices;
            _categoryServices = categoryServices;
            _reviewServices = reviewServices;
        }

        public async Task<ActionResult> ListByCategory(string category)
        {
            IEnumerable<Book> books;
            string currentCategory = string.Empty;

            if (category.IsBlank())
            {
                books = await _bookServices.GetAsync(orderBy: b => b.OrderBy(x => x.Title), page: 1, pageSize: 10);
                currentCategory = "All of Books";
            }
            else
            {
                books = await _bookServices.GetAsync(filter: b => b.Category.CategoryName == category, orderBy: b => b.OrderBy(x => x.Title), page: 1, pageSize: 10);

                currentCategory = category;
            }

            return View(new BooksListViewModel
            {
                Books = books,
                CurrentCategory = currentCategory
            });
        }

        public async Task<ActionResult> ListByPrice(decimal priceLevel)
        {
            IEnumerable<Book> books;
            decimal currentPrice = decimal.Zero;

            if (priceLevel < 0)
            {
                books = await _bookServices.GetAsync(orderBy: b => b.OrderBy(x => x.Title), page: 1, pageSize: 10);
                currentPrice = 0;
            }
            else
            {
                books = await _bookServices.GetAsync(filter: b => b.Price < priceLevel, orderBy: b => b.OrderBy(x => x.Title), page: 1, pageSize: 10);

                currentPrice = priceLevel;
            }

            return View(new BooksListByPriceViewModel
            {
                Books = books,
                CurrentPrice = currentPrice
            });
        }

        public async Task<ActionResult> ListByAuthor(string authorName)
        {
            IEnumerable<Book> books;
            string currentAuthor = string.Empty;

            if (string.IsNullOrEmpty(authorName))
            {
                books = await _bookServices.GetAsync(orderBy: b => b.OrderBy(x => x.Title), page: 1, pageSize: 10);
                currentAuthor = "Tất Cả Tác Giả";
            }
            else
            {
                books = await _bookServices.GetAsync(filter: b => b.Author.AuthorName == authorName, orderBy: b => b.OrderBy(x => x.Title), page: 1, pageSize: 10);

                currentAuthor = authorName;
            }

            return View(new BooksListByAuthorViewModel
            {
                Books = books,
                CurrentAuthor = currentAuthor
            });
        }

        public async Task<ActionResult> ListByPublisher(string publisherName)
        {
            IEnumerable<Book> books;
            string currentPublisher = string.Empty;

            if (string.IsNullOrEmpty(publisherName))
            {
                books = await _bookServices.GetAsync(orderBy: b => b.OrderBy(x => x.Title), page: 1, pageSize: 10);
                currentPublisher = "Tất Cả Các Nhà Xuất Bản";
            }
            else
            {
                books = await _bookServices.GetAsync(filter: b => b.Publisher.PublisherName == publisherName, orderBy: b => b.OrderBy(x => x.Title), page: 1, pageSize: 10);

                currentPublisher = publisherName;
            }

            return View(new BooksListByPublisherViewModel
            {
                Books = books,
                CurrentPublisher = currentPublisher
            });
        }

        public async Task<ActionResult> Details(int id)
        {
            var book = await _bookServices.GetByIdAsync(id);
            if (book == null)
                return HttpNotFound();

            var user = User.Identity.GetApplicationUser();


            var bookDetailViewModel = new BookDetailViewModel()
            {
                Book = book                
            };
            return View(bookDetailViewModel);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public async Task<ActionResult> Details(int id, string review)
        {
            var book = await _bookServices.GetByIdAsync(id);
            var user = User.Identity.GetApplicationUser();
            if (book == null)
                return HttpNotFound();

            string encodeReview = HtmlEncoder.Default.Encode(review);

            var bookReview = new Review()
            {
                UserId = user.Id,
                BookId = book.BookId,
                Comment = encodeReview,
                CreatedDate = DateTimeOffset.Now,
                IsActive = true
            };
            await _reviewServices.CreateAsync(bookReview);

            return RedirectToAction("Details");
        }
    }
}

BookStore/BookStore.Presentation/Areas/Admin/Views/BookManagement/AddBook.cshtml
@model BookEditViewModel

@{
    ViewData["Title"] = "Add Book | Book Store";
}

<h2>Add Book:</h2>
<hr />
<form action="/Admin/BookManagement/AddBook" method="post" class="row form-horizontal" enctype="multipart/form-data">
    @Html.AntiForgeryToken()
    <div class="col">
        <div class="form-group">
            <label class="control-label">Title:</label>
            <div>
                <input type="text" class="form-control" name="Title" />
                @Html.ValidationMessageFor(m => m.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label">Summary:</label>
            <div>
                <textarea class="form-control" name="Summary" id="ckeditor"></textarea>
                @Html.ValidationMessageFor(m => m.Summary, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label" for="ImgUrl">Image Thumbnail:</label>
            <div class="custom-file">
                <input type="file" class="custom-file-input" id="validatedCustomFile" name="ImgUrl" onchange="readURL(this)">
                <label class="custom-file-label" for="validatedCustomFile">Choose an image</label>
                <img id="FileImage" src="~/Assets/images/avatar-1.png" name="ImgUrl" alt="your image" class="img-thumbnail" width="200" />
                @Html.ValidationMessageFor(m => m.ImgUrl, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="col">
        <div class="form-group">
            <label class="control-label">Price:</label>
            <div>
                <input type="number" class="form-control" name="Price" min="1" />
                @Html.ValidationMessageFor(m => m.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label">Quantity:</label>
            <div>
                <input type="number" class="form-control" name="Quantity" min="1"/>
                @Html.ValidationMessageFor(m => m.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label">Category:</label>
            <div class="input-group mb-3">
                @Html.DropDownListFor(m => m.CategoryId, new SelectList(ViewBag.Categories, "Value", "Text"), "Select a category", new { @class = "form-control", @id = "CateList" })
                <div class="input-group-append">
                    <button class="btn btn-outline-primary" type="button" data-toggle="modal" data-target="#ModalAddCategory" onclick="resetModalCat();">+</button>
                </div>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label">Author:</label>
            <div class="input-group mb-3">
                @Html.DropDownListFor(m => m.AuthorId, new SelectList(ViewBag.Authors, "Value", "Text"), "Select an author", new { @class = "form-control", @id = "AutList" })
                <div class="input-group-append">
                    <button class="btn btn-outline-primary" type="button" data-toggle="modal" data-target="#ModalAddAuthor" onclick="resetModalAut();">+</button>
                </div>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label">Publisher:</label>
            <div class="input-group mb-3">
                @Html.DropDownListFor(m => m.PublisherId, new SelectList(ViewBag.Publishers, "Value", "Text"), "Select a publisher", new { @class = "form-control", @id = "PubList" })
                <div class="input-group-append">
                    <button class="btn btn-outline-primary" type="button" data-toggle="modal" data-target="#ModalAddPublisher" onclick="resetModalPub();">+</button>
                </div>
            </div>
        </div>

        <div class="form-group form-check">
            @Html.EditorFor(model => model.IsActive)
            <label class="form-check-label" for="IsActive">Is Active?</label>
            @Html.ValidationMessageFor(m => m.IsActive, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            <input type="submit" class="btn btn-primary" value="Add" />
            <a class="btn btn-secondary" href="/Admin/BookManagement/Index">Cancel</a>
        </div>
    </div>
</form>

@Html.Partial("_AddCategoryModal")
@Html.Partial("_AddAuthorModal")
@Html.Partial("_AddPublisherModal")

@section scripts {
    <script src="~/Assets/js/ckeditor/ckeditor.js"></script>
    <script src="~/Assets/js/ckeditor/ckeditorconfig.js"></script>
    <script src="~/Assets/js/readurl.js"></script>
    <script src="~/Assets/js/addcategory.js"></script>
    <script src="~/Assets/js/addauthor.js"></script>
    <script src="~/Assets/js/addpublisher.js"></script>
    <script>
        $(function () {
            $(document).on('change', ':file', function () {
                var input = $(this), numFiles = input.get(0).files ? input.get(0).files.length : 1,
                    label = input.val().replace(/\\/g, '/').replace(/.*\//, ''); input.trigger('fileselect', [numFiles, label]);
            });
            $(document).ready(function () {
                $(':file').on('fileselect', function (event, numFiles, label) {
                    var input = $(this).parents('.custom-file').find('.custom-file-label'),
                        log = numFiles > 1 ? numFiles + ' files selected' : label; if (input.length) { input.text(log); } else { if (log) alert(log); }
                });
            });
        });
    </script>
}

BookStore/BookStore.Presentation/Areas/Admin/Views/BookManagement/EditBook.cshtml
 @model BookEditViewModel

@{
    ViewData["Title"] = "Edit Book | " + Model.Title + " | Book Store";
}
<h2>Edit Book:</h2>
<hr />
<form action="/Admin/BookManagement/EditBook" method="post" class="row form-horizontal" enctype="multipart/form-data">
    @Html.AntiForgeryToken()
    @Html.HiddenFor(x => x.BookId)
    <div class="col">
        <div class="form-group">
            <label class="control-label">Title:</label>
            <div>
                <input type="text" class="form-control" name="Title" value="@Model.Title" />
                @Html.ValidationMessageFor(m => m.Title, "", new { @class = "text-danger" })

            </div>
        </div>

        <div class="form-group">
            <label class="control-label">Summary:</label>
            <div>
                <textarea class="form-control" name="Summary" id="ckeditor">@Model.Summary</textarea>
                @Html.ValidationMessageFor(m => m.Summary, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label" for="ImgUrl">Image Thumbnail:</label>
            <div class="form-row">
                <div class="col-6">
                    <input type="file" class="custom-file-input" id="validatedCustomFile" name="ImgUrl" onchange="readURL(this)">
                    <label class="custom-file-label" for="validatedCustomFile">Choose an image</label>
                </div>
                <div class="col-6">
                    <img id="FileImage" src="~/Assets/images/@Model.ImageUrl" name="ImgUrl" alt="your image" class="img-thumbnail" width="200" />
                    <input type="text" class="form-control" name="ImgUrl" value="@Model.ImageUrl" required hidden="hidden" />
                    @Html.ValidationMessageFor(m => m.ImageUrl, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>

    <div class="col">
        <div class="form-group">
            <label class="control-label">Price:</label>
            <div>
                <input type="number" class="form-control" name="Price" value="@Model.Price" />
                @Html.ValidationMessageFor(m => m.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label">Quantity:</label>
            <div>
                <input type="number" class="form-control" name="Quantity" value="@Model.Quantity" />
                @Html.ValidationMessageFor(m => m.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label">Category:</label>
            <div>
                @Html.DropDownListFor(model => model.CategoryId, (IEnumerable<SelectListItem>)ViewBag.Categories, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label">Author:</label>
            <div>
                @Html.DropDownListFor(model => model.AuthorId, (IEnumerable<SelectListItem>)ViewBag.Authors, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label">Publisher:</label>
            <div>
                @Html.DropDownListFor(model => model.PublisherId, (IEnumerable<SelectListItem>)ViewBag.Publishers, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group form-check">
            @Html.EditorFor(model => model.IsActive)
            <label class="form-check-label" for="IsActive">Is Active?</label>
        </div>

        <div class="form-group">
            <input type="submit" class="btn btn-primary" value="Update" />
            <a class="btn btn-secondary" href="/Admin/BookManagement/Index">Cancel</a>
        </div>
    </div>
</form>

@section scripts {
    <script src="~/Assets/js/ckeditor/ckeditor.js"></script>
    <script src="~/Assets/js/ckeditor/ckeditorconfig.js"></script>
    <script src="~/Assets/js/readurl.js"></script>
    <script src="~/Assets/js/addcategory.js"></script>
    <script src="~/Assets/js/addauthor.js"></script>
    <script src="~/Assets/js/addpublisher.js"></script>
} 

BookStore/BookStore.Presentation/Areas/Admin/Views/BookManagement/Index.cshtml
@model PaginatedList<Book>

@{
    ViewData["Title"] = "Book Management | Book Store";
}

<h2>Book Management</h2>

<hr />
<div>
    <a href="@Url.Action("AddBook", "BookManagement")" class="btn btn-primary float-left">Add Book</a>

    <form action="@Url.Action("Index", "BookManagement")" method="get" class="form-inline float-right">

        @*<div class="form-group mx-sm-3 mb-2">
                <label class="my-1 mr-2" for="sortOrder">Order By:</label>
                <select class="custom-select my-1 mr-sm-2" id="orderBy">
                    <option value="1">Price Up</option>
                    <option value="2">Price Down</option>
                </select>
            </div>*@
        <div class="form-group mx-sm-3 mb-2">
            <label for="inputSearch" class="control-label mr-3">Input: </label>
            <input type="text" class="form-control mr-3" id="inputSearch" name="searchString" value="@ViewData["CurrentFilter"]" placeholder="Input....">
            <input type="submit" class=" form-control btn btn-primary mr-3" value="Search" /> |
            <a href="/Admin/BookManagement/Index" class="btn btn-default">Back to Full List</a>
        </div>

    </form>
</div>

@if (!Model.Any())
{
    <tr><td colspan="3" class="text-center">Don't have a book yet.</td></tr>
}
else
{
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            @{
                var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
                var nextDisabled = !Model.HasNextPage ? "disabled" : "";
                ViewBag.PageRange = 3;
            }
            <li class="page-item">
                <a href="@Url.Action("Index", "BookManagement", new { sortOrder=ViewData["CurrentSort"], page=1, currentFilter=ViewData["CurrentFilter"] })"
                   class="btn page-link @prevDisabled"><<</a>
            <li class="page-item">
                <a href="@Url.Action("Index", "BookManagement", new { sortOrder=ViewData["CurrentSort"], page=(Model.PageIndex - 1 <= 0 ? 1 : Model.PageIndex - 1), currentFilter=ViewData["CurrentFilter"] })"
                   class="btn page-link @prevDisabled"><</a>
            </li>
            @for (int i = 1; i <= Model.TotalPages; i++)
            {
                if (i >= Model.PageIndex - ViewBag.PageRange && i <= Model.PageIndex + ViewBag.PageRange)
                {
                    <li class="page-item">
                        <a class="@(i==Model.PageIndex ? "Current" : "") page-link"
                           href="@Url.Action("Index", "BookManagement", new { sortOrder=ViewData["CurrentSort"], page=i, currentFilter=ViewData["CurrentFilter"] })">@i</a>
                    </li>
                }
                @*<li class="page-item"><a class="page-link" href="@Url.Action("Index", "BookManagement", new { sortOrder=ViewData["CurrentSort"], page=i, currentFilter=ViewData["CurrentFilter"] })">@i</a></li>*@
            }
            <li class="page-item">
                <a href="@Url.Action("Index", "BookManagement", new { sortOrder=ViewData["CurrentSort"], page=(Model.PageIndex + 1 > Model.TotalPages ? Model.TotalPages : Model.PageIndex + 1), currentFilter=ViewData["CurrentFilter"] })"
                   class="btn page-link @nextDisabled">></a>
            <li class="page-item">
                <a href="@Url.Action("Index", "BookManagement", new { sortOrder=ViewData["CurrentSort"], page=(Model.TotalPages), currentFilter=ViewData["CurrentFilter"] })"
                   class="btn page-link @nextDisabled">>></a>
        </ul>
    </nav>
    <table class="table table-condensed table-bordered">
        <tr class="d-flex">
            <th class="col-md-2">Image</th>
            <th class="col-md-4">
                <a href="@Url.Action("Index", "BookManagement", new { sortOrder = ViewData["TitleSortParm"], currentFilter = ViewData["CurrentFilter"] })">Title</a>
            </th>
            <th class="col-md-2">
                <a href="@Url.Action("Index", "BookManagement", new { sortOrder = ViewData["PriceSortParm"], currentFilter = ViewData["CurrentFilter"] })">Price</a>
            </th>
            <th class="col-md-1">
                <a href="@Url.Action("Index", "BookManagement", new { sortOrder = ViewData["QuantitySortParm"], currentFilter = ViewData["CurrentFilter"] })">Quantity</a>
            </th>
            <th class="col-md-1">Is Active</th>
            <th class="col-md-2">Manage</th>
        </tr>

        @foreach (var book in Model)
        {
            <tr class="d-flex">
                <td class="col-md-2">
                    <img style="max-width:150px;" src="~/Assets/images/@book.ImageUrl" alt="@book.Title" />
                </td>
                <td class="col-md-4">
                    <a href="@Url.Action("Details", "Book", new { id = book.BookId, area = "" })">@book.Title</a>
                </td>
                <td class="col-md-2">
                    @book.Price.ToString("C0", CultureInfo.CreateSpecificCulture("vi-VN"))
                </td>
                <td class="col-md-1">
                    @book.Quantity
                </td>
                <td class="col-md-1">
                    @book.IsActive
                </td>
                <td class="col-md-2">
                    <form action="@Url.Action("DeleteBook","BookManagement", new { id=book.BookId })" method="post">
                        <a href="@Url.Action("EditBook","BookManagement", new { id=book.BookId })" class="btn btn-primary">Edit</a>
                        <button type="submit" onclick="return confirm('Are you sure to delete this book?');" class="btn btn-danger">Delete</button>
                    </form>
                </td>
            </tr>
        }
    </table>
}